# Generated by Django 5.2.7 on 2026-02-23 21:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0004_applicationconfiguration_barcode_asn_prefix_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="barcode_max_pages",
            field=models.PositiveIntegerField(
                null=True,
                verbose_name="Sets the maximum pages for barcode",
            ),
        ),
    ]
